mod-name: StationPartsExpansionRedux
package:
  include-dependencies: true  # Include dependencies in the package
  included-gamedata:
    - StationPartsExpansionRedux
  included-support:  # Include these root-level files in packages
    - readme.txt
    - changelog.txt
dependencies:  # Configure dependencies
  ModuleManager:
    version: 4.1.0
    location: s3
  B9PartSwitch:
    version: 2.12.1
    location: s3
  NearFutureProps:
    tag: 0.6.1
    location: github
    repository: ChrisAdderley/NearFutureProps
deploy:
  SpaceDock:
    enabled: true  # activate/deactivate this deployment script
    mod-id: 1682  # The Spacedock mod ID for deployment
  CurseForge:
    enabled: true  # activate/deactivate this deployment script
    mod-id: 289367  # The CurseForge mod ID for deployment
  GitHub:
    enabled: true  # activate/deactivate this deployment script
